---
- name: install docker 
  import_tasks: InstallPackages.yml

- name: Init
  import_tasks: init.yml

- name: Create Apache container
  docker_container:
    name: webapp
    image: httpd
    ports:
      - "{{apache_listen_port}}:{{apache_listen_port}}"
    volumes:
      - "{{ working_dir }}/index.html:/usr/local/apache2/htdocs/index.html"
